baseURL: https://cybereducation-io.github.io/
languageCode: en-us
title: cybereducation.io
theme: hugo-fresh
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
