---
navbarlogo:
  image: logos/fresh.svg
  link: /
hero:
  title: hugo fresh documentation
  subtitle: Probably the best hugo theme out there!
  buttontext: Go to docs
  buttonlink: getstarted
  image: illustrations/worker.svg
navbar:
- title: GitHub
  url: https://github.com/StefMa/hugo-fresh
  button: true
